# Generated by Django 4.0.3 on 2022-10-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('import_href', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('date_app', models.DateField()),
                ('time_app', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('created', models.DateField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vip', serialize=False, to='service_rest.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicetech', to='service_rest.technician'),
        ),
        migrations.AddField(
            model_name='service',
            name='vin_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vin_service', to='service_rest.automobilevo'),
        ),
    ]
